### ISSUE TITLE
how do you install/use the presets in 1.12.2?

### ISSUE THREAD

**Issue by JadianRadiator** [glowredman/modularmaterials#2]
how do you install/use the presets in 1.12.2?
[copy here](https://www.curseforge.com/minecraft/mc-mods/modular-materials?comment=9)

**Comment by glowredman** [comment]
Presets for 1.12.2 are located [here](https://github.com/glowredman/modularmaterials/tree/new-api/presets). Navigate to your desired directory and download the `materials.json` or `types.json`. A file on GitHub can be downloaded like this:
1. Click on the file
![grafik](https://user-images.githubusercontent.com/35727266/140607354-5ded067b-7594-4ba6-aab9-73da95f2a8a1.png)
2. Click on `Raw`:
![grafik](https://user-images.githubusercontent.com/35727266/140607422-1b4d1967-d375-4969-82ca-8c54e1b55b08.png)
3. Save the file (usually `Ctrl` + `S`) to the `<game-dir>/config/modularmaterials/`-folder (if a prompt opens saying that this file already exists, confirm that you want to replace it):
![grafik](https://user-images.githubusercontent.com/35727266/140607600-140a957d-4b0f-4e1a-8ce0-ad2a7429c1e1.png)
4. Done!

I hope this helps :)

**Comment by JadianRadiator** [comment]
it doesn't because there's more than one types.json
And I don't know what each of them do,
so I assumed they could be placed/put together to all go in.

**Comment by JadianRadiator** [comment]
I just looked through them, they don't all go together.
I'll be looking through them to try combining them.

**Comment by glowredman** [comment]
They just have an increasing amount of types configured (vanilla -> basic -> advanced -> extended). You only need one of them. If you want to know what types they have defined, there is a table [here](https://github.com/glowredman/modularmaterials/blob/new-api/presets/types/TYPES.md).

**Comment by JadianRadiator** [comment]
When I went through them the only significant difference was that the
unused entries were disabled.
But we're still in it.
So I enabled all of them from one of the configs.
