### ISSUE TITLE
Any recommendations on how to gray-out a pre-existing colored texture to than add as a type/template in Modular Materials?

### ISSUE THREAD

**Issue by JadianRadiator** [glowredman/modularmaterials#3]
Any recommendations on how to gray-out a pre-existing colored texture to than add as a type/template in Modular Materials?
I'm wanting/needing to know so I can use Modular Materials to add the Base/Modern Metals mods' metals as Immersive Engineering sheetmetal.

**Comment by glowredman** [comment]
Using GIMP, you can desaturate the image: https://docs.gimp.org/2.10/en/gimp-filter-desaturate.html
