### ISSUE TITLE
GTCE formula and MM tooltip added formula is duplecated

### ISSUE THREAD

**Issue by smalIjam** [glowredman/modularmaterials#4]
![20211113_194941](https://user-images.githubusercontent.com/94219648/141619917-c894949a-41c8-4439-8478-874b7b09e703.png)

i tried to adding disappeared GT stuff with using MM, but when i applied it, it duplecated formula twice.
is there any key to solve this?

**Comment by glowredman** [comment]
Go to the `materials.json`-config file, go to the material you want to edit and remove the `"Be"` from the tooltip entry:
```json
"beryllium": {
      ...
      "tooltip": [
        "Be"
      ]
    },
```

**Comment by smalIjam** [comment]
yes, i know that's the clearest solution, but i wanna apply chem formula to thing which GTCE cannot apply formula (ex:triple, quadruple plate)

**Comment by glowredman** [comment]
There are two possibile solutions
- Disable all item types from a material which GT already adds (for example all dust, ingots, plates from beryllium)
-> `"enabledTypes "` in `materials.json`
- Disable the display of tooltips for a type (`hasTooltip` in `types.json`)

The second option is much more infelxible and invasive so I would suggest you try the first option first.

**Comment by smalIjam** [comment]
now it works. thanks!
