### ISSUE TITLE
Crash on Lead Fluid Registration 

### ISSUE THREAD

**Issue by theTyrfing** [glowredman/modularmaterials#7]
Game version:
1.12

Java Version:
Java 8

Mod version:
Modular Materials 0.5-beta

Step to reproduce:
1) Use the Json Provide with Modular Materials
2) Boot game with Json.
3) Crash

Crash report:
(Not available at the moment, still working out a way to upload it) 

Notes
The weirdest part is, I added other materials fine, iron, gold , silver etc; but lead for keeps crashing my game
There is 1 unregistered fluids

Fluid name : lead, type: net.minecraftforge.fluids.Fluid

Is there anything wrong with this json?
[materials.txt](https://github.com/glowredman/modularmaterials/files/11734503/materials.txt)

**Comment by glowredman** [comment]
The config should be valid. Can you send the other config files too? What other mods are you using?

PS: You can use [GitHub Gist](https://gist.github.com/) or [mclo.gs](https://mclo.gs/) to upload the crash report.

**Comment by theTyrfing** [comment]
currently. I have this: https://gist.github.com/theTyrfing/ca40561272664ac5b9d82535b0a318c6
Although, with this instance I am running just modular materials though. In another instance, there are multiple mods as listed below. 
![image](https://github.com/glowredman/modularmaterials/assets/7342368/3da5275c-4685-4b9b-a757-908260ddc3e5)

**Comment by theTyrfing** [comment]
Here are the crash logs too
https://gist.github.com/theTyrfing/77ddfdf0399210710dd9b2e483d606c0

**Comment by glowredman** [comment]
Any type you reference in your `materials.json` file *must* exist in your `types.json` file.
As you only use the example `types.json`, all of these need an entry:
```json
{
   "materials":{
      "iron":{
         ...
         "enabledTypes":{
            "block":false,
            "bolt":true,
            "crushed":true,
            "grinded":true,
            "separatedGrav":true,
            "separatedFroth":true,
            "separatedMag":true,
            "roasted":true,
            "leached":true,
            "centrifuged":true,
            "electrolyzed":true,
            "crystalyzed":true,
            "sintered":true,
            "dust":true,
            "dust_small":true,
            "dust_tiny":true,
            "foil":true,
            "gear":true,
            "gear_small":true,
            "item_casing":true,
            "ore":true,
            "plate":true,
            "plate_dense":true,
            "ring":true,
            "rod":true,
            "rod_long":true,
            "rotor":true,
            "round":true,
            "screw":true,
            "spring":true,
            "spring_small":true,
            "wire":true
         },
         ...
      "lead":{
         ...
         "enabledTypes":{
            "block":false,
            "bolt":true,
            "crushed":true,
            "grinded":true,
            "separatedGrav":true,
            "separatedFroth":true,
            "separatedMag":true,
            "roasted":true,
            "leached":true,
            "centrifuged":true,
            "electrolyzed":true,
            "crystalyzed":true,
            "sintered":true,
            "dust":true,
            "dust_small":true,
            "dust_tiny":true,
            "foil":true,
            "gear":true,
            "gear_small":true,
            "item_casing":true,
            "liquid":false,
            "ore":true,
            "plate":true,
            "plate_dense":true,
            "ring":true,
            "rod":true,
            "rod_long":true,
            "rotor":true,
            "round":true,
            "screw":true,
            "spring":true,
            "spring_small":true,
            "wire":true
         },
         ...
      }
   }
}
```
You can find many of these here: https://github.com/glowredman/modularmaterials/tree/new-api/presets/types

**Comment by theTyrfing** [comment]
> 

Like this? https://gist.github.com/theTyrfing/2d3ebac9058392265db1cf5651281d94

As I think the crash still does happen with this. Although right now, it is currently giving a null point exception error. It was giving a lead fluid resignation error before. Same one as crash log 2 in the links above. 
What could be going on?

**Comment by theTyrfing** [comment]
To reiterate from your post before:
1) I was missing a liquid type in my types.json
2) A bug was identified and you have made new release that fixes it.

I am closing this issue as that has resolved it. Thank you very much. However, a new problem arose but that would be a new issue.
